# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.prototipo.com:
    container_name: orderer.prototipo.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/prototipo.com/orderers/orderer.prototipo.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/prototipo.com/orderers/orderer.prototipo.com/tls/:/var/hyperledger/orderer/tls
    - orderer.prototipo.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.prototipo.com:
    container_name: peer0.org1.prototipo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.prototipo.com
      - CORE_PEER_ADDRESS=peer0.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.prototipo.com/peers/peer0.org1.prototipo.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.prototipo.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.org1.prototipo.com:
    container_name: peer1.org1.prototipo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.prototipo.com
      - CORE_PEER_ADDRESS=peer1.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.prototipo.com/peers/peer1.org1.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.prototipo.com/peers/peer1.org1.prototipo.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.prototipo.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.org2.prototipo.com:
    container_name: peer0.org2.prototipo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.prototipo.com
      - CORE_PEER_ADDRESS=peer0.org2.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.prototipo.com/peers/peer0.org2.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.prototipo.com/peers/peer0.org2.prototipo.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.prototipo.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.org2.prototipo.com:
    container_name: peer1.org2.prototipo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.prototipo.com
      - CORE_PEER_ADDRESS=peer1.org2.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.prototipo.com/peers/peer1.org2.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.prototipo.com/peers/peer1.org2.prototipo.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.prototipo.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.org3.prototipo.com:
    container_name: peer0.org3.prototipo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.prototipo.com
      - CORE_PEER_ADDRESS=peer0.org3.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org3.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.prototipo.com/peers/peer0.org3.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.prototipo.com/peers/peer0.org3.prototipo.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org3.prototipo.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.org3.prototipo.com:
    container_name: peer1.org3.prototipo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.prototipo.com
      - CORE_PEER_ADDRESS=peer1.org3.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.prototipo.com/peers/peer1.org3.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.prototipo.com/peers/peer1.org3.prototipo.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org3.prototipo.com:/var/hyperledger/production

    ports:
      - 12051:7051
      - 12053:7053

  peer0.org4.prototipo.com:
    container_name: peer0.org4.prototipo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org4.prototipo.com
      - CORE_PEER_ADDRESS=peer0.org4.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org4.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org4.prototipo.com/peers/peer0.org4.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org4.prototipo.com/peers/peer0.org4.prototipo.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org4.prototipo.com:/var/hyperledger/production
    ports:
      - 13051:7051
      - 13053:7053

  peer1.org4.prototipo.com:
    container_name: peer1.org4.prototipo.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org4.prototipo.com
      - CORE_PEER_ADDRESS=peer1.org4.prototipo.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org4.prototipo.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.prototipo.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org4.prototipo.com/peers/peer1.org4.prototipo.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org4.prototipo.com/peers/peer1.org4.prototipo.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org4.prototipo.com:/var/hyperledger/production
    ports:
      - 14051:7051
      - 14053:7053
